
volumes:
 db_data: {}

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
